### ISSUE TITLE
Cannot get pwsphinx client to work with zphinx-zerver

### ISSUE THREAD

**Issue by rolfschr** [stef/zphinx-zerver#2]
Hi,

I'm trying to let `sphinx` (the client impl from `pwdsphinx`) communicate with `zphinx-zerver`. Here is a screenshot of the two. On the left, I run `zphinx-zerver`. On the right, I run `sphinx`.

![image](https://user-images.githubusercontent.com/1188465/117126266-d1b80900-ad9a-11eb-92ad-5d844a182a1f.png)

I figure the problem stems from the SSL key/cert files. The files have been created previously and are known to work for `pwdsphinx` client<->server. I did not create any *.der file as outlined in the readme - the instructions are not clear enough (for me) to produce the expected files:

```bash
$ openssl req -new -x509 -key server.der -keyform DER -out cert.pem -days 360                                                                                                                                  Can't open server.der for reading, No such file or directory
140569518163264:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:69:fopen('server.der','rb')
140569518163264:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:76:
unable to load Private Key
```

The [docker readme](https://github.com/D3vl0per/zphinx-zerver-docker) contains some further instructions but are not clear for me neither. Could you give step-by-step instructions on how to create the SSL certificates for zphinx-zerver, ideally in a way that the pwdsphinx client can use them, too.

**Comment by stef** [comment]
for testing purposes this should be enough to generate a self-signed cert (i just tested it it works for me):

```
openssl ecparam -genkey -out ssl_key.pem -name secp384r1
openssl req -new -nodes -x509 -sha256 -key ssl_key.pem -out ssl_cert.pem -days 365 -subj '/CN=localhost'
```

the problem is that currently zphinx is compiled to only initialize the ssl engine with `br_ssl_server_init_minf2c()` which only supports ecdsa keymaterial.

I documented this in the `ratelimiter` branch - which is scheduled to be merged into master as soon as androsphinx also supports the ratelimiter and some protocol changes...

**Comment by rolfschr** [comment]
Hi,

thanks for the quick reply. I can confirm that these settings allow to let the pwdsphinx client communicate with zsphinx-zerver.
